syntax = "proto3";

package djs;

message RegisterWorkerRequest {
  int32 cpu_cores = 1;
  float mem_size = 2;
  float disk_size = 3;
  float cpu_freq = 4;
  string os = 5;
  string name = 6;
}

message RegisterWorkerReply {
  bool ok = 1;
  string message = 2;
  int32 worker_id = 3;
}

message SubmitJobRequest {
  int32 client_id = 1;
  string job_type = 2;
  map<string, string> params = 3;
}

message SubmitJobReply {
  string job_id = 1;
  bool accepted = 2;
  string message = 3;
}

message GetJobStatusRequest {
  string job_id = 1;
}

message GetJobStatusReply {
  string status = 1;
  string assigned_worker_id = 2;
}

message GetJobRequest {
  int32 worker_id = 1;
}

message GetJobResponse {
  int32 job_id = 1;
  string job_type = 2;
  map<string, string> params = 3;
}

message RegisterClientRequest {
  string hostname = 1;
}

message RegisterClientResponse {
  int32 client_id = 1;
  bool ok = 2;
  string message = 3;
}

message ReportJobResultRequest {
  int32 worker_id = 1;
  int32 job_id = 2;
  bool success = 3;
  string message = 4;
  string artifact_url = 5;
  string metrics_json = 6;
}

message ReportJobResultReply {
  bool ok = 1;
}

service SchedulerService {
  rpc RegisterWorker(RegisterWorkerRequest) returns (RegisterWorkerReply);
  rpc SubmitJob(SubmitJobRequest) returns (SubmitJobReply);
  rpc GetJobStatus(GetJobStatusRequest) returns (GetJobStatusReply);
  rpc GetJob(GetJobRequest) returns (GetJobResponse);
  rpc RegisterClient(RegisterClientRequest) returns (RegisterClientResponse);
  rpc ReportJobResult(ReportJobResultRequest) returns (ReportJobResultReply);
}
